//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessReviewApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;

    [Table("Business")]
    public class Business
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int BusinessID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
        public string County { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string URLPhoto1 { get; set; }
        public string URLPhoto2 { get; set; }
        public string URLPhoto3 { get; set; }
        public string URLPhoto4 { get; set; }
        public string URLPhoto5 { get; set; }
        public Nullable<decimal> DecimalLatitude { get; set; }
        public Nullable<decimal> DecimalLongtitude { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string WebsiteURL { get; set; }
        public Nullable<int> PriceRating { get; set; }
        public Nullable<int> SuitableForFamilies { get; set; }
        public Nullable<int> FastFood { get; set; }

        public Business()
        {
            this.Reviews = new HashSet<Review>();
        }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
